# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import processor
import sys
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 621, 71))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(54)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.btnSelectFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFile.setGeometry(QtCore.QRect(170, 130, 421, 61))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.btnSelectFile.setFont(font)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(170, 390, 421, 61))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(26)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 270, 151, 51))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.videoType = QtWidgets.QComboBox(self.centralwidget)
        self.videoType.setGeometry(QtCore.QRect(360, 210, 221, 51))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(24)
        self.videoType.setFont(font)
        self.videoType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.videoType.setObjectName("videoType")
        self.videoType.addItem("")
        self.videoType.addItem("")
        self.keyFrameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.keyFrameInput.setGeometry(QtCore.QRect(370, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(24)
        self.keyFrameInput.setFont(font)
        self.keyFrameInput.setObjectName("keyFrameInput")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 330, 181, 51))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.blurIntensity = QtWidgets.QComboBox(self.centralwidget)
        self.blurIntensity.setGeometry(QtCore.QRect(360, 330, 221, 51))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(24)
        self.blurIntensity.setFont(font)
        self.blurIntensity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.blurIntensity.setObjectName("blurIntensity")
        self.blurIntensity.addItem("")
        self.blurIntensity.addItem("")
        # self.blurIntensity.addItem("")
        # self.blurIntensity.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnSelectFile.clicked.connect(lambda: self.openFileNameDialog())
        self.btnStart.clicked.connect(lambda: self.startGenerating())
        self.video_path = None

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Panorama   Generator"))
        self.btnSelectFile.setText(_translate("MainWindow", "Select   Video"))
        self.btnStart.setText(_translate("MainWindow", "Start    Generating"))
        self.label_2.setText(_translate("MainWindow", "Key Frames"))
        self.label_3.setText(_translate("MainWindow", "Video Type"))
        self.videoType.setItemText(0, _translate("MainWindow", " Horizontal"))
        self.videoType.setItemText(1, _translate("MainWindow", " Vertical"))
        self.keyFrameInput.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "Blur Intensity"))
        self.blurIntensity.setItemText(0, _translate("MainWindow", " No Blur"))
        # self.blurIntensity.setItemText(1, _translate("MainWindow", " Less Blur"))
        self.blurIntensity.setItemText(1, _translate("MainWindow", " Moderate Blur"))
        # self.blurIntensity.setItemText(3, _translate("MainWindow", " More Blur"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new file"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save a file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))

    def openFileNameDialog(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(MainWindow, "QFileDialog.getOpenFileName()", "",
                                                  "All Files (*);;Video Files (*.mp4)", options=options)
        if fileName:
            justFileName = os.path.basename(fileName)
            self.btnSelectFile.setText(f"File selected: {justFileName}")
            self.video_path = fileName

    def show_popup(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Critical)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    @pyqtSlot()
    def startGenerating(self):
        if not self.video_path:  # Check if a video file has been selected
            self.show_popup("Error", "Please Select A Video File Before Generating.")
            return

        try:
            num_frames = int(self.keyFrameInput.text())
            if num_frames <= 0:  # Assuming key frames should be a positive integer
                raise ValueError("Key frames must be a positive integer.")

        except ValueError as e:
            self.show_popup("Input Error", str(e))
            return

        blur_intensity = self.blurIntensity.currentText()

        video_type = self.videoType.currentText()
        if video_type == " Horizontal":
            processor.process_horizontal_video(self.video_path, num_frames, blur_intensity)
        elif video_type == " Vertical":
            processor.process_vertical_video(self.video_path, num_frames, blur_intensity)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
